server:
  port: 8086
  servlet:
    context-path: /test

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.93.132:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never #自动化初始表结构
      #quartz的数据表在：quartz-2.3.0.jar!\org\quartz\impl\jdbcjobstore\tables_mysql_innodb.sql
  redis:
      database: 0 # Redis 数据库索引（默认为 0）
      host: 192.168.93.132 # Redis 服务器地址
      port: 6379 # Redis 服务器连接端口
      password: # Redis 服务器连接密码（默认为空）
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-idle: 8 # 连接池中的最大空闲连接 默认 8
          min-idle: 0 # 连接池中的最小空闲连接 默认 0


logging:
  config: classpath:log4j2-dev.xml